"""Preset model configurations for Galaxy New.

API keys are NOT stored here — users enter them in the UI,
and they're saved to the system keyring.
"""

PRESET_MODELS: list[dict] = [
    {"name": "DeepSeek V3", "model": "deepseek-chat",
     "base_url": "https://api.deepseek.com",
     "context_length": 64000,
     "capabilities": {"vision": False, "function_calling": True, "streaming": True},
     "desc": "DeepSeek 最新对话模型，性价比极高"},
    {"name": "DeepSeek R1", "model": "deepseek-reasoner",
     "base_url": "https://api.deepseek.com",
     "context_length": 64000,
     "capabilities": {"vision": False, "function_calling": False, "streaming": True, "reasoning": True},
     "desc": "DeepSeek 推理模型，擅长复杂逻辑"},
    {"name": "DeepSeek V4 Pro", "model": "deepseek-v4-pro",
     "base_url": "https://api.deepseek.com",
     "context_length": 64000,
     "capabilities": {"vision": True, "function_calling": False, "streaming": True, "manual_tools": True},
     "desc": "DeepSeek 最新旗舰，需手动工具协议"},
    {"name": "OpenAI GPT-4o", "model": "gpt-4o",
     "base_url": "https://api.openai.com/v1",
     "context_length": 128000,
     "capabilities": {"vision": True, "function_calling": True, "structured_output": True, "streaming": True},
     "desc": "OpenAI 旗舰多模态模型"},
    {"name": "OpenAI GPT-4o-mini", "model": "gpt-4o-mini",
     "base_url": "https://api.openai.com/v1",
     "context_length": 128000,
     "capabilities": {"vision": True, "function_calling": True, "structured_output": True, "streaming": True},
     "desc": "OpenAI 轻量快速模型"},
    {"name": "OpenAI GPT-4.1", "model": "gpt-4.1",
     "base_url": "https://api.openai.com/v1",
     "context_length": 1000000,
     "capabilities": {"vision": True, "function_calling": True, "structured_output": True, "streaming": True},
     "desc": "OpenAI 百万上下文多模态模型"},
    {"name": "OpenAI o3-mini", "model": "o3-mini",
     "base_url": "https://api.openai.com/v1",
     "context_length": 200000,
     "capabilities": {"vision": False, "function_calling": True, "streaming": True, "reasoning": True},
     "desc": "OpenAI 推理模型"},
    {"name": "Claude Sonnet 4 (OpenRouter)", "model": "anthropic/claude-sonnet-4",
     "base_url": "https://openrouter.ai/api/v1",
     "context_length": 200000,
     "capabilities": {"vision": True, "function_calling": True, "streaming": True},
     "desc": "Anthropic 旗舰，需 OpenRouter Key"},
    {"name": "Qwen VL Max (DashScope)", "model": "qwen-vl-max",
     "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
     "context_length": 32000,
     "capabilities": {"vision": True, "function_calling": True, "streaming": True},
     "desc": "通义千问视觉模型"},
    {"name": "Qwen-Plus", "model": "qwen-plus",
     "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
     "context_length": 128000,
     "capabilities": {"vision": False, "function_calling": True, "streaming": True},
     "desc": "阿里云通义千问"},
    {"name": "GLM-4 (智谱)", "model": "glm-4-plus",
     "base_url": "https://open.bigmodel.cn/api/paas/v4",
     "context_length": 128000,
     "capabilities": {"vision": True, "function_calling": True, "streaming": True},
     "desc": "智谱 AI 大模型"},
    {"name": "Moonshot (月之暗面)", "model": "moonshot-v1-128k",
     "base_url": "https://api.moonshot.cn/v1",
     "context_length": 128000,
     "capabilities": {"vision": False, "function_calling": True, "streaming": True},
     "desc": "Kimi 同款模型，128K 上下文"},
    {"name": "Ollama Local", "model": "llama3",
     "base_url": "http://localhost:11434/v1",
     "context_length": 8192,
     "capabilities": {"vision": False, "function_calling": False, "streaming": True},
     "desc": "本地运行，需先装 Ollama"},
]
